marks = []
m1 = int(input("Enter marks of Student 1:"))
marks.append(m1)
m2 = int(input("Enter marks of Student 2:"))
marks.append(m2)
m3 = int(input("Enter marks of Student 3:"))
marks.append(m3)
m4 = int(input("Enter marks of Student 4:"))
marks.append(m4)
m5 = float(input("Enter marks of Student 5:"))
marks.append(m5)
m6 = (input("Enter marks of Student 6:"))
marks.append(m6)
print("1.Marks of students: ", marks)
print("2.Sorted marks of students: ", sorted(marks))
print("3.Reversed marks of students: ", list(reversed(marks)))    
print("4.Average marks of students: ",sum(map(int,marks))/len(marks))
print("5.Maximum marks of students: ", max(marks))
print("6.Minimum marks of students: ", min(marks))
print("7.Total marks of students: ", sum(map(int,marks)))
print("8.Number of students: ", len(marks))