#write a program to input eight numbers from the user and display all the unique numbers(once)
s = set()
n1 = input("Enter number 1: ")
s.add(n1)
n2 = input("Enter number 2: ")
s.add(n2)
n3 = input("Enter number 3: " )
s.add(n3)
n4 = input("Enter number 4: ")
s.add(n4)
n5 = input("Enter number 5: ")
s.add(n5)
n6 = input("Enter number 6: ")
s.add(n6)
n7 = input("Enter number 7: ")
s.add(n7)
n8 = input("Enter number 8: ")
s.add(n8)
print(s)