s = {}
l1 = input("Enter first language: ")
n1 = input("Enter first name: ")
s.update({n1:l1})
l2 = input("Enter second language: ")
n2 = input("Enter second name: ")
s.update({n2:l2})
l3 = input("Enter third language: ")
n3 = input("Enter third name: ")
s.update({n3:l3})
l4 = input("Enter fourth language: ")
n4 = input("Enter fourth name: ")
s.update({n4:l4})
print(s)
